---
- name: Grundkonfiguration des Home Servers
  hosts: home_servers
  become: true
  gather_facts: true

  tasks:
    - name: Aktuellen administrativen Benutzer prüfen
      ansible.builtin.command:
        cmd: id -un
      register: effective_user
      changed_when: false
      check_mode: false

    - name: Prüfen, ob sudo funktioniert
      ansible.builtin.assert:
        that:
          - effective_user.stdout == "root"
        fail_msg: "Ansible besitzt keine Root-Rechte."
        success_msg: "Ansible arbeitet erfolgreich als root."

    - name: Paket tree installieren
      ansible.builtin.apt:
        name: tree
        state: present
        update_cache: true
        cache_valid_time: 86400