---
github_runner_github_owner: "KandlerLi"
github_runner_github_repositories:
  - id: "dyndns"
    repository: "dyndns"

shared_ingress_acme_email: "julian.kandler@outlook.com"
nextcloud_aio_reverse_proxy_enabled: true
shared_ingress_enabled: true
shared_ingress_start: true
shared_ingress_agent_enabled: true
home_agent_frontend_network_enabled: true
open_webui_enabled: true
shared_ingress_open_webui_enabled: true
nextcloud_tools_allowed_root: Shared/AI Workspace
